//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diner_Smash.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Gameplay : global::System.Configuration.ApplicationSettingsBase {
        
        private static Gameplay defaultInstance = ((Gameplay)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Gameplay())));
        
        public static Gameplay Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float Gary_MenuTime {
            get {
                return ((float)(this["Gary_MenuTime"]));
            }
            set {
                this["Gary_MenuTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public float Gary_EatTime {
            get {
                return ((float)(this["Gary_EatTime"]));
            }
            set {
                this["Gary_EatTime"] = value;
            }
        }
    }
}
